### PR TITLE
✨ IMPROVE: Conditionally load  on pages

### PR DESCRIPTION
**Pull request by choldgraf**
This conditionally loads thebe so that the JS is only loaded on pages that *have a `thebe` button*.

supercedes https://github.com/executablebooks/sphinx-thebe/pull/14

Also pins our Sphinx lower bound to 3.5 since that is when conditional loading was introduced.

### CODE REVIEW

**Comment by akhmerov** [comment]
What happens if the button is provided by the theme?

**Comment by choldgraf** [comment]
Right now it will purely look for `ThebeButtonNode`. I guess the assumption is that if the theme is hard-coding a button then they could also manually load the JS itself? What do you think is a good solution there?

**Comment by akhmerov** [comment]
Perhaps checking if thebe is configured and there are cells to execute? This seems to be agnostic with respect to the execution method.

**Comment by choldgraf** [comment]
@akhmerov I opened up this one to track this: https://github.com/executablebooks/sphinx-thebe/issues/34

I think the main question is "are there cells to execute". e.g., how do you define what that means? (wanna take conversation over there?)

**Pull request merged**
