### PR TITLE
Sphinx 7 support

### PR DESCRIPTION
**Pull request by LecrisUT**
This one cannot be built because of dependency hell in the testing dependencies. Any advice?

See my fork pr for action runner https://github.com/LecrisUT/sphinx-thebe/pull/2

### CODE REVIEW

**Comment by choldgraf** [comment]
Given that this package is relatively simple and likely will not test the Sphinx API too much, I'd suggest we remove the upper bound pin on Sphinx in general. I'd suggest that we open an issue to track this decision, and if after one or two more major releases we have had problems associated with API changes that would have been caught by a major version pin, we can change the policy back. Does that make sense?

**Comment by LecrisUT** [comment]
I already removed the upper pin in the setup.py file. Yes, we can remove the 5,6 versioned requirements as soon as a simple test passes. But I had install failures there right now. Let me fix the CI so I can show. Also do you want to track future releases as well in the CI?

**Comment by LecrisUT** [comment]
Oh sorry all the actions pass. I think I have this confused with another package that broke some support :thinking:. I will remove the intermediate sphinx requirements and this can be merged I think

**Comment by LecrisUT** [comment]
Also, there's a chicken-and-egg problem with `sphinx-book-theme` to support sphinx 7. Should I add a temporary commit pointing it to my branch there to check the CI here?

**Comment by choldgraf** [comment]
hmmm - I feel it'd be better if we actually didn't use the book theme in the testing suite since it's got some unnecessary complexity that we probably aren't testing with anyway. What if we either changed the theme to Alabaster on the fly in the test, or created a little dummy test site to run that didn't have the book theme dependencies.

**Comment by LecrisUT** [comment]
Let me give it a quick try to see if we can just use the default/builtin themes. Hopefully they are not hard-coded in the tests

**Comment by LecrisUT** [comment]
I don't understand the tests well enough to figure out what would be a minimum testing suite. Current version complains as:
```
Warning, treated as error:
role 'sub-ref' is already registered, it will be overridden
```

It seems that the minimum test dependencies are `myst-parser` and `myst-nb` because:
```python
    # Check for MyST-NB cell structure to make sure it stays the same
    # If this breaks, we'll need to update our default cell selectors
    soup_nb = BeautifulSoup(
        Path(sphinx_build.path_pg_ntbk).read_text(), "html.parser"
    )
```

**Comment by LecrisUT** [comment]
I need help with creating minimal tests, I am not familiar with the project to make the necessary mwe

**Comment by LecrisUT** [comment]
I'll open a new one for CI stuff

**Pull request closed without merging**
